devices:
  - name: "UniFi Switch"
    ip: "10.10.40.1"

  - name: "Synology NAS"
    ip: "10.10.40.91"

  - name: "ENCODER-SERVICE"
    ip: "10.10.40.88"

  - name: "ENCODER-SERMON"
    ip: "10.10.40.89"

  - name: "DECODER-PRODUCTION"
    ip: "10.10.40.39"
    type: "ping"
  - name: "DECODER-FOH"
    ip: "10.10.40.37"
    type: "ping"
  - name: "DECODER-CONFIDENCE"
    ip: "10.10.40.38"
    type: "ping"
  - name: "QSYS_CORE"
    ip: "10.10.40.50"
    type: "ping"
  - name: "AUD_PROJECTOR_RIGHT"
    ip: "10.10.40.2"
    type: "ping"
  - name: "AUD_PROJECTOR_LEFT"
    ip: "10.10.40.2"
    type: "ping"
  - name: "LOBBY_PROJECTOR"
    ip: "10.10.40.5"
    type: "ping"
  - name: "ATEM 1 M/E Advanced Panel"
    ip: "10.10.40.21"
    type: "ping"
  - name: "ATEM 4 M/E Broadcast Studio 4K"
    ip: "10.10.40.20"
    type: "ping"
  - name: "AUD_PROJECTOR_Center"
    ip: "10.10.40.3"
    type: "ping"
  - name: "ATEM ROUTER - MainRack"
    ip: "10.10.40.187"
    type: "ping"
  - name: "ATEM 1 M/E Advanced Panel"
    ip: "10.10.40.21"
    type: "ping"
  - name: "Resi Encoder - Agawam"
    ip: "10.10.40.129"
    type: "ping"